[book]
authors = ["Bryant Biggs"]
language = "en"
src = "docs"
title = "Terraform Module Data"

[output]

[output.linkcheck]

[output.html]
git-repository-url = "https://github.com/clowdhaus/terraform-module-data/tree/main"
edit-url-template = "https://github.com/clowdhaus/terraform-module-data/edit/main/{path}"
additional-css = [
  "./theme/overrides.css",
  "./theme/catppuccin.css",
  "./theme/catppuccin-admonish.css",
]

default-theme = "latte"
preferred-dark-theme = "frappe"
