name: Update data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *' # 11pm EST
    # - cron: '0 15 * * *' # 11am EST

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TERRAFORM_MODULE_DATA }}

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: rust-src

      - name: Build
        run: cargo build --release

      - name: Update
        run: ./collect.sh
        env:
          GH_TOKEN: ${{ secrets.TERRAFORM_MODULE_DATA }}
          TERRAFORM_MODULE_DATA: ${{ secrets.TERRAFORM_MODULE_DATA }}

      - name: Pre-commit
        run: |
          python -m pip install pre-commit
          pre-commit autoupdate && pre-commit run -a || true

      - name: Commit & push
        uses: EndBug/add-and-commit@v9
        if: always()
        with:
          author_name: bryantbiggs
          author_email: ${{ secrets.AUTHOR_EMAIL }}
          message: 'chore: Daily data collection and graph update'
          push: true
