name: Update data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *' # 11pm EST
    # - cron: '0 15 * * *' # 11am EST

permissions: {}

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          token: ${{ secrets.TERRAFORM_MODULE_DATA }}

      - name: Install Rust
        uses: dtolnay/rust-toolchain@67ef31d5b988238dd797d409d6f9574278e20537 # master
        with:
          toolchain: nightly
          components: rust-src

      - name: Build
        run: cargo build --release

      - name: Update
        run: ./collect.sh
        env:
          GH_TOKEN: ${{ secrets.TERRAFORM_MODULE_DATA }}
          TERRAFORM_MODULE_DATA: ${{ secrets.TERRAFORM_MODULE_DATA }}

      - name: Pre-commit
        continue-on-error: true
        run: |
          python -m pip install pre-commit
          pre-commit run -a

      - name: Commit & push
        uses: EndBug/add-and-commit@290ea2c423ad77ca9c62ae0f5b224379612c0321 # v10.0.0
        with:
          author_name: bryantbiggs
          author_email: ${{ secrets.AUTHOR_EMAIL }}
          message: 'chore: daily data collection update'
          push: true
